// Code generated by protoc-gen-go.
// source: todo.proto
// DO NOT EDIT!

/*
Package todo is a generated protocol buffer package.

It is generated from these files:
	todo.proto

It has these top-level messages:
	ListRequest
	ListResponse
	Item
*/
package todo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListRequest struct {
	Auth   string `protobuf:"bytes,1,opt,name=auth" json:"auth,omitempty"`
	Limit  int64  `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
	Offset int64  `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ListResponse struct {
	Valid bool    `protobuf:"varint,1,opt,name=valid" json:"valid,omitempty"`
	Items []*Item `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ListResponse) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type Item struct {
	Title string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Body  string `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
}

func (m *Item) Reset()                    { *m = Item{} }
func (m *Item) String() string            { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()               {}
func (*Item) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*ListRequest)(nil), "todo.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "todo.ListResponse")
	proto.RegisterType((*Item)(nil), "todo.Item")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Todo service

type TodoClient interface {
	// TodoList returns a list of todo items.
	List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error)
}

type todoClient struct {
	c           client.Client
	serviceName string
}

func NewTodoClient(serviceName string, c client.Client) TodoClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "todo"
	}
	return &todoClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *todoClient) List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Todo.List", in)
	out := new(ListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Todo service

type TodoHandler interface {
	// TodoList returns a list of todo items.
	List(context.Context, *ListRequest, *ListResponse) error
}

func RegisterTodoHandler(s server.Server, hdlr TodoHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Todo{hdlr}, opts...))
}

type Todo struct {
	TodoHandler
}

func (h *Todo) List(ctx context.Context, in *ListRequest, out *ListResponse) error {
	return h.TodoHandler.List(ctx, in, out)
}

func init() { proto.RegisterFile("todo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x90, 0xc1, 0x4a, 0xc5, 0x30,
	0x10, 0x45, 0x69, 0x9b, 0x16, 0x3b, 0x75, 0xe3, 0x20, 0x12, 0x5c, 0x85, 0xae, 0xba, 0xb1, 0x48,
	0xc5, 0x5f, 0x10, 0x04, 0x41, 0x08, 0xfe, 0x40, 0x4b, 0x52, 0x0c, 0xb4, 0x4e, 0x35, 0x53, 0xe1,
	0xfd, 0xfd, 0x23, 0x49, 0x17, 0xdd, 0xdd, 0x33, 0x61, 0x2e, 0x27, 0x03, 0xc0, 0x64, 0xa8, 0xdf,
	0xfe, 0x88, 0x09, 0x45, 0xc8, 0xed, 0x27, 0x34, 0x1f, 0xce, 0xb3, 0xb6, 0xbf, 0xbb, 0xf5, 0x8c,
	0x08, 0x62, 0xdc, 0xf9, 0x5b, 0x66, 0x2a, 0xeb, 0x6a, 0x1d, 0x33, 0xde, 0x43, 0xb9, 0xb8, 0xd5,
	0xb1, 0xcc, 0x55, 0xd6, 0x15, 0x3a, 0x01, 0x3e, 0x40, 0x45, 0xf3, 0xec, 0x2d, 0xcb, 0x22, 0x8e,
	0x0f, 0x6a, 0xdf, 0xe0, 0x36, 0x15, 0xfa, 0x8d, 0x7e, 0xbc, 0x0d, 0xdb, 0xff, 0xe3, 0xe2, 0x4c,
	0xac, 0xbc, 0xd1, 0x09, 0x50, 0x41, 0xe9, 0xd8, 0xae, 0x5e, 0xe6, 0xaa, 0xe8, 0x9a, 0x01, 0xfa,
	0x28, 0xf6, 0xce, 0x76, 0xd5, 0xe9, 0xa1, 0x7d, 0x06, 0x11, 0x30, 0xec, 0xb3, 0xe3, 0xc5, 0x1e,
	0x4a, 0x09, 0x82, 0xe7, 0x44, 0xe6, 0x12, 0x95, 0x6a, 0x1d, 0xf3, 0xf0, 0x0a, 0xe2, 0x8b, 0x0c,
	0xe1, 0x13, 0x88, 0x60, 0x80, 0x77, 0xa9, 0xf4, 0xf4, 0xbd, 0x47, 0x3c, 0x8f, 0x92, 0xe0, 0x54,
	0xc5, 0x73, 0xbc, 0x5c, 0x03, 0x00, 0x00, 0xff, 0xff, 0x87, 0x0d, 0x9d, 0x8b, 0x1c, 0x01, 0x00,
	0x00,
}
