// Code generated by protoc-gen-go.
// source: todo.proto
// DO NOT EDIT!

/*
Package todo is a generated protocol buffer package.

It is generated from these files:
	todo.proto

It has these top-level messages:
	Request
	Response
	Item
*/
package todo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Auth   string `protobuf:"bytes,1,opt,name=auth" json:"auth,omitempty"`
	Limit  int64  `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
	Offset int64  `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Response struct {
	Valid bool    `protobuf:"varint,1,opt,name=valid" json:"valid,omitempty"`
	Items []*Item `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type Item struct {
	Title string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Body  string `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
}

func (m *Item) Reset()                    { *m = Item{} }
func (m *Item) String() string            { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()               {}
func (*Item) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*Item)(nil), "Item")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Service service

type ServiceClient interface {
	// TodoList returns a list of todo items.
	List(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type serviceClient struct {
	c           client.Client
	serviceName string
}

func NewServiceClient(serviceName string, c client.Client) ServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "service"
	}
	return &serviceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *serviceClient) List(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Service.List", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Service service

type ServiceHandler interface {
	// TodoList returns a list of todo items.
	List(context.Context, *Request, *Response) error
}

func RegisterServiceHandler(s server.Server, hdlr ServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Service{hdlr}, opts...))
}

type Service struct {
	ServiceHandler
}

func (h *Service) List(ctx context.Context, in *Request, out *Response) error {
	return h.ServiceHandler.List(ctx, in, out)
}

func init() { proto.RegisterFile("todo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x34, 0x8f, 0xcd, 0x6a, 0x84, 0x30,
	0x14, 0x85, 0xf1, 0x5f, 0x6f, 0x77, 0xa1, 0x94, 0x50, 0x37, 0xe2, 0xa2, 0xb8, 0x0a, 0xc5, 0xae,
	0xfb, 0x00, 0xa5, 0xb3, 0xca, 0x3c, 0x81, 0x8e, 0x57, 0x26, 0xa0, 0x13, 0xc7, 0x5c, 0x85, 0x79,
	0xfb, 0x21, 0x89, 0xb3, 0xbb, 0xdf, 0x81, 0x73, 0xf9, 0x0e, 0x00, 0xe9, 0x41, 0x8b, 0x65, 0xd5,
	0xa4, 0xeb, 0x7f, 0xc8, 0x24, 0xde, 0x37, 0x34, 0xc4, 0x18, 0xc4, 0xdd, 0x46, 0x57, 0x1e, 0x54,
	0x41, 0x53, 0x48, 0x77, 0xb3, 0x77, 0x48, 0x26, 0x35, 0x2b, 0xe2, 0x61, 0x15, 0x34, 0x91, 0xf4,
	0xc0, 0x3e, 0x20, 0xd5, 0xe3, 0x68, 0x90, 0x78, 0xe4, 0xe2, 0x83, 0xea, 0x5f, 0xc8, 0x25, 0x9a,
	0x45, 0xdf, 0x0c, 0xda, 0xe6, 0xde, 0x4d, 0x6a, 0x70, 0xef, 0x72, 0xe9, 0x81, 0x95, 0x90, 0x28,
	0xc2, 0xd9, 0xf0, 0xb0, 0x8a, 0x9a, 0xb7, 0x36, 0x11, 0x7f, 0x84, 0xb3, 0xf4, 0x59, 0xfd, 0x0d,
	0xb1, 0x45, 0x5b, 0x25, 0x45, 0x13, 0x1e, 0x26, 0x1e, 0xac, 0x5e, 0xaf, 0x87, 0x87, 0x33, 0x29,
	0xa4, 0xbb, 0xdb, 0x2f, 0xc8, 0xce, 0xb8, 0xee, 0xea, 0x82, 0xac, 0x84, 0xf8, 0xa4, 0x0c, 0xb1,
	0x5c, 0x1c, 0x7b, 0x3e, 0x0b, 0xf1, 0x92, 0xe9, 0x53, 0x37, 0xf6, 0xe7, 0x19, 0x00, 0x00, 0xff,
	0xff, 0x5b, 0x4e, 0xc6, 0x27, 0xfa, 0x00, 0x00, 0x00,
}
