// Code generated by protoc-gen-go.
// source: db.proto
// DO NOT EDIT!

/*
Package db is a generated protocol buffer package.

It is generated from these files:
	db.proto

It has these top-level messages:
	TodoListRequest
	TodoEntry
	TodoListResponse
	UserRequest
	UserResponse
	UserProfile
*/
package db

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// TodoListRequest is used for fetching a user's todo list
type TodoListRequest struct {
	User   string `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Limit  int64  `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
	Offset int64  `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
}

func (m *TodoListRequest) Reset()                    { *m = TodoListRequest{} }
func (m *TodoListRequest) String() string            { return proto.CompactTextString(m) }
func (*TodoListRequest) ProtoMessage()               {}
func (*TodoListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type TodoEntry struct {
	Title string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Body  string `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
}

func (m *TodoEntry) Reset()                    { *m = TodoEntry{} }
func (m *TodoEntry) String() string            { return proto.CompactTextString(m) }
func (*TodoEntry) ProtoMessage()               {}
func (*TodoEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type TodoListResponse struct {
	Exists  bool         `protobuf:"varint,1,opt,name=exists" json:"exists,omitempty"`
	Entries []*TodoEntry `protobuf:"bytes,2,rep,name=entries" json:"entries,omitempty"`
}

func (m *TodoListResponse) Reset()                    { *m = TodoListResponse{} }
func (m *TodoListResponse) String() string            { return proto.CompactTextString(m) }
func (*TodoListResponse) ProtoMessage()               {}
func (*TodoListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TodoListResponse) GetEntries() []*TodoEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type UserRequest struct {
	User string `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *UserRequest) Reset()                    { *m = UserRequest{} }
func (m *UserRequest) String() string            { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()               {}
func (*UserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type UserResponse struct {
	Exists  bool         `protobuf:"varint,1,opt,name=exists" json:"exists,omitempty"`
	Profile *UserProfile `protobuf:"bytes,2,opt,name=profile" json:"profile,omitempty"`
}

func (m *UserResponse) Reset()                    { *m = UserResponse{} }
func (m *UserResponse) String() string            { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()               {}
func (*UserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UserResponse) GetProfile() *UserProfile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type UserProfile struct {
	User string `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Pass string `protobuf:"bytes,3,opt,name=pass" json:"pass,omitempty"`
}

func (m *UserProfile) Reset()                    { *m = UserProfile{} }
func (m *UserProfile) String() string            { return proto.CompactTextString(m) }
func (*UserProfile) ProtoMessage()               {}
func (*UserProfile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterType((*TodoListRequest)(nil), "TodoListRequest")
	proto.RegisterType((*TodoEntry)(nil), "TodoEntry")
	proto.RegisterType((*TodoListResponse)(nil), "TodoListResponse")
	proto.RegisterType((*UserRequest)(nil), "UserRequest")
	proto.RegisterType((*UserResponse)(nil), "UserResponse")
	proto.RegisterType((*UserProfile)(nil), "UserProfile")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Todo service

type TodoClient interface {
	// TodoList returns a list of todo items.
	TodoList(ctx context.Context, in *TodoListRequest, opts ...client.CallOption) (*TodoListResponse, error)
}

type todoClient struct {
	c           client.Client
	serviceName string
}

func NewTodoClient(serviceName string, c client.Client) TodoClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "todo"
	}
	return &todoClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *todoClient) TodoList(ctx context.Context, in *TodoListRequest, opts ...client.CallOption) (*TodoListResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Todo.TodoList", in)
	out := new(TodoListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Todo service

type TodoHandler interface {
	// TodoList returns a list of todo items.
	TodoList(context.Context, *TodoListRequest, *TodoListResponse) error
}

func RegisterTodoHandler(s server.Server, hdlr TodoHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Todo{hdlr}, opts...))
}

type Todo struct {
	TodoHandler
}

func (h *Todo) TodoList(ctx context.Context, in *TodoListRequest, out *TodoListResponse) error {
	return h.TodoHandler.TodoList(ctx, in, out)
}

// Client API for Profiler service

type ProfilerClient interface {
	// UserProfile returns a user profile.
	UserProfile(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*UserResponse, error)
}

type profilerClient struct {
	c           client.Client
	serviceName string
}

func NewProfilerClient(serviceName string, c client.Client) ProfilerClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "profiler"
	}
	return &profilerClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *profilerClient) UserProfile(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*UserResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Profiler.UserProfile", in)
	out := new(UserResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Profiler service

type ProfilerHandler interface {
	// UserProfile returns a user profile.
	UserProfile(context.Context, *UserRequest, *UserResponse) error
}

func RegisterProfilerHandler(s server.Server, hdlr ProfilerHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Profiler{hdlr}, opts...))
}

type Profiler struct {
	ProfilerHandler
}

func (h *Profiler) UserProfile(ctx context.Context, in *UserRequest, out *UserResponse) error {
	return h.ProfilerHandler.UserProfile(ctx, in, out)
}

func init() { proto.RegisterFile("db.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x52, 0xdb, 0x4a, 0xf4, 0x30,
	0x10, 0x66, 0x0f, 0xff, 0x6e, 0x3b, 0xdd, 0x1f, 0xd7, 0x20, 0x52, 0xbc, 0xaa, 0x41, 0xa4, 0x78,
	0x11, 0xa1, 0xa2, 0x3e, 0x81, 0x17, 0x82, 0xc8, 0x12, 0xf5, 0x01, 0xb6, 0x74, 0x0a, 0x81, 0x6e,
	0x53, 0x33, 0x59, 0x70, 0xdf, 0x5e, 0x92, 0xb4, 0x1e, 0x16, 0xd1, 0xbb, 0x39, 0xf4, 0x9b, 0xef,
	0xd0, 0x40, 0x54, 0x95, 0xa2, 0x33, 0xda, 0x6a, 0xfe, 0x04, 0x07, 0xcf, 0xba, 0xd2, 0x0f, 0x8a,
	0xac, 0xc4, 0xd7, 0x2d, 0x92, 0x65, 0x0c, 0xa6, 0x5b, 0x42, 0x93, 0x8e, 0xb2, 0x51, 0x1e, 0x4b,
	0x5f, 0xb3, 0x23, 0xf8, 0xd7, 0xa8, 0x8d, 0xb2, 0xe9, 0x38, 0x1b, 0xe5, 0x13, 0x19, 0x1a, 0x76,
	0x0c, 0x33, 0x5d, 0xd7, 0x84, 0x36, 0x9d, 0xf8, 0x71, 0xdf, 0xf1, 0x6b, 0x88, 0xdd, 0xd1, 0xbb,
	0xd6, 0x9a, 0x9d, 0x83, 0x5a, 0x65, 0x1b, 0xec, 0xef, 0x85, 0xc6, 0x91, 0x94, 0xba, 0xda, 0xf9,
	0x7b, 0xb1, 0xf4, 0x35, 0x5f, 0xc1, 0xf2, 0x53, 0x0b, 0x75, 0xba, 0x25, 0x74, 0x14, 0xf8, 0xa6,
	0xc8, 0x92, 0x87, 0x47, 0xb2, 0xef, 0xd8, 0x19, 0xcc, 0xb1, 0xb5, 0x46, 0x21, 0xa5, 0xe3, 0x6c,
	0x92, 0x27, 0x05, 0x88, 0x0f, 0x4a, 0x39, 0xac, 0xf8, 0x29, 0x24, 0x2f, 0x84, 0xe6, 0x17, 0x67,
	0xfc, 0x11, 0x16, 0xe1, 0x93, 0x3f, 0x08, 0xcf, 0x61, 0xde, 0x19, 0x5d, 0xab, 0x06, 0xbd, 0xe6,
	0xa4, 0x58, 0x08, 0x87, 0x5b, 0x85, 0x99, 0x1c, 0x96, 0xfc, 0x3e, 0x50, 0xf6, 0xf3, 0x1f, 0xc3,
	0x64, 0x30, 0x6d, 0xd7, 0x1b, 0x1c, 0xbc, 0xbb, 0xda, 0xcd, 0xba, 0x35, 0x91, 0x0f, 0x32, 0x96,
	0xbe, 0x2e, 0x6e, 0x61, 0xea, 0x3c, 0xb1, 0x4b, 0x88, 0x86, 0x5c, 0xd8, 0x52, 0xec, 0xfd, 0xae,
	0x93, 0x43, 0xb1, 0x1f, 0x5a, 0x71, 0x03, 0x51, 0xcf, 0x6f, 0xd8, 0xc5, 0x77, 0x3d, 0x41, 0xf5,
	0x80, 0xfd, 0x2f, 0xbe, 0x7a, 0x2f, 0x67, 0xfe, 0x4d, 0x5c, 0xbd, 0x07, 0x00, 0x00, 0xff, 0xff,
	0x6d, 0x14, 0x9e, 0x8f, 0x1f, 0x02, 0x00, 0x00,
}
